#################################################################  
# Aimple Makefile  
#      1. ι€θ¦ζΎεΌζ‡ε®λ²Ί“δ½α«½®γ€εη§°οη¦  
#      2. make ε?make cleanε¤„η†εΎ—δΈε¥?ε―ΉδΊεΊΒ°Όθ¦δΉε ι™¤ε†α«Ό–θ―‘οΌθ¦δΉοί ζ“δ½?οΌ? 
#################################################################  

CC=gcc
CFLAGS = -Wall
DEBUG = y

export TEST
TEST = BOSS

ifeq ($(DEBUG), y)
	CFLAGS += -g
else
	CFLAGS += -O2
endif

include subdir.mk

RM = -rm -rf

MAKE = make
target = dsop.bin

__OBJS = $(foreach s,$(SUBDIRS),$(s)/$(s).o) 

$(target):$(__OBJS)
	echo $(__OBJS)
	for dir in $(SUBDIRS);do $(MAKE) -C $$dir all || exit 1;done
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
	echo $(TEST)

clean:
	@for dir in $(SUBDIRS); do make -C $$dir clean|| exit 1; done
	$(RM) $(__OBJS) $(target) *.bak *~

.PHONY: all clean 

