DIR_LIB_RESOURCE = $(DIR_LIB)/resource

SRC_NSDB += $(DIR_LIB_RESOURCE)/appendbuf.c
SRC_NSDB += $(DIR_LIB_RESOURCE)/bitmap.c
SRC_NSDB += $(DIR_LIB_RESOURCE)/epoll.c
SRC_NSDB += $(DIR_LIB_RESOURCE)/id.c
SRC_NSDB += $(DIR_LIB_RESOURCE)/lilist.c
SRC_NSDB += $(DIR_LIB_RESOURCE)/timer.c
SRC_NSDB += $(DIR_LIB_RESOURCE)/event.c

SRC_NSDB_C += $(DIR_LIB_RESOURCE)/bitmap.c
SRC_NSDB_C += $(DIR_LIB_RESOURCE)/epoll.c
SRC_NSDB_C += $(DIR_LIB_RESOURCE)/id.c
SRC_NSDB_C += $(DIR_LIB_RESOURCE)/lilist.c
SRC_NSDB_C += $(DIR_LIB_RESOURCE)/timer.c
SRC_NSDB_C += $(DIR_LIB_RESOURCE)/appendbuf.c

