
#所有需要的obj文件
#OBJS = main.o
#OBJS += ../public/dataop/opdata.o
#OBJS += ../public/include/string.o
#OBJS += ../web/socket.o
#OBJS += ../web/web_ProcReq.o

#bin需要的obj
bin_OBJS =  main.o
bin_OBJS += ../public/include/string.o
bin_OBJS += ../public/dataop/list.o
bin_OBJS += ../public/dataop/table_type.o
bin_OBJS += ../public/dataop/opdata.o
bin_OBJS += ../public/dataop/nsdb.o



t:
	echo $(TOP_DIR)

